leaderboard = [
    {
        "#": "**",
        "Model": "Random",
        "Prompt": "-",
        "Setting": "-",
        "Size": "-",
        "Backbone": "-",
        "Link": "-",
        "Lang": 32.70,
        "Natural": 30.62,
        "Social": 26.71,
        "Physical": 32.97,
        "SocialC": 22.22,
        "Temporal": 20.33,
        "Algebra": 35.71,
        "Geometry": 27.50,
        "Theory": 23.81,
        "Total": 28.56
    },
    {
        "#": "1",
        "Model": "Kosmos-2-2B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "2",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2306.14824",
        "Lang": 10.43,
        "Natural": 28.61,
        "Social": 21.18,
        "Physical": 33.33,
        "SocialC": 17.77,
        "Temporal": 28.46,
        "Algebra": 21.43,
        "Geometry": 21.25,
        "Theory": 14.29,
        "Total": 23.17
    },
    {
        "#": "2",
        "Model": "Kosmos-2-2B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "2",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2306.14824",
        "Lang": 18.48,
        "Natural": 24.14,
        "Social": 14.65,
        "Physical": 30.00,
        "SocialC": 14.46,
        "Temporal": 9.76,
        "Algebra": 17.14,
        "Geometry": 18.75,
        "Theory": 0.00,
        "Total": 18.68
    },
    {
        "#": "3",
        "Model": "Kosmos-2-2B",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "2",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2306.14824",
        "Lang": 0.00,
        "Natural": 0.00,
        "Social": 0.00,
        "Physical": 1.11,
        "SocialC": 0.00,
        "Temporal": 0.00,
        "Algebra": 0.00,
        "Geometry": 0.00,
        "Theory": 0.00,
        "Total": 0.04
    },
    {
        "#": "4",
        "Model": "Kosmos-2-2B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "2",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2306.14824",
        "Lang": 0.00,
        "Natural": 0.00,
        "Social": 0.16,
        "Physical": 2.22,
        "SocialC": 7.44,
        "Temporal": 1.63,
        "Algebra": 0.00,
        "Geometry": 0.00,
        "Theory": 0.00,
        "Total": 0.99
    },
    {
        "#": "5",
        "Model": "InstructBLIP-7B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 30.81,
        "Natural": 32.31,
        "Social": 27.55,
        "Physical": 60.00,
        "SocialC": 66.94,
        "Temporal": 39.02,
        "Algebra": 35.71,
        "Geometry": 31.25,
        "Theory": 33.33,
        "Total": 36.11
    },
    {
        "#": "6",
        "Model": "InstructBLIP-7B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 38.39,
        "Natural": 30.01,
        "Social": 26.43,
        "Physical": 80.00,
        "SocialC": 70.25,
        "Temporal": 33.33,
        "Algebra": 30.71,
        "Geometry": 21.25,
        "Theory": 19.05,
        "Total": 35.76
    },
    {
        "#": "7",
        "Model": "InstructBLIP-13B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 38.39,
        "Natural": 30.52,
        "Social": 26.27,
        "Physical": 76.67,
        "SocialC": 70.66,
        "Temporal": 35.77,
        "Algebra": 30.00,
        "Geometry": 22.50,
        "Theory": 19.05,
        "Total": 35.94
    },
    {
        "#": "8",
        "Model": "InstructBLIP-13B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 38.39,
        "Natural": 30.01,
        "Social": 27.55,
        "Physical": 80.00,
        "SocialC": 70.25,
        "Temporal": 33.33,
        "Algebra": 30.71,
        "Geometry": 21.25,
        "Theory": 19.05,
        "Total": 36.07
    },
    {
        "#": "9",
        "Model": "InstructBLIP-13B",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 16.59,
        "Natural": 27.84,
        "Social": 22.77,
        "Physical": 54.44,
        "SocialC": 52.89,
        "Temporal": 30.08,
        "Algebra": 27.86,
        "Geometry": 28.75,
        "Theory": 28.57,
        "Total": 29.25
    },
    {
        "#": "10",
        "Model": "InstructBLIP-13B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://arxiv.org/abs/2305.06500",
        "Lang": 13.27,
        "Natural": 26.95,
        "Social": 24.84,
        "Physical": 62.22,
        "SocialC": 67.36,
        "Temporal": 41.46,
        "Algebra": 25.00,
        "Geometry": 25.00,
        "Theory": 23.81,
        "Total": 31.28
    },
    {
        "#": "11",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 43.13,
        "Natural": 37.16,
        "Social": 26.43,
        "Physical": 66.67,
        "SocialC": 58.26,
        "Temporal": 30.89,
        "Algebra": 22.14,
        "Geometry": 35.00,
        "Theory": 14.29,
        "Total": 36.63
    },
    {
        "#": "12",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 38.86,
        "Natural": 33.59,
        "Social": 25.48,
        "Physical": 71.11,
        "SocialC": 65.29,
        "Temporal": 39.02,
        "Algebra": 29.29,
        "Geometry": 16.25,
        "Theory": 4.76,
        "Total": 35.81
    },
    {
        "#": "13",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 34.12,
        "Natural": 32.18,
        "Social": 25.32,
        "Physical": 65.56,
        "SocialC": 57.85,
        "Temporal": 41.46,
        "Algebra": 24.29,
        "Geometry": 31.25,
        "Theory": 28.57,
        "Total": 34.43
    },
    {
        "#": "14",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "7",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 26.54,
        "Natural": 35.50,
        "Social": 28.66,
        "Physical": 62.22,
        "SocialC": 55.79,
        "Temporal": 44.72,
        "Algebra": 29.29,
        "Geometry": 31.25,
        "Theory": 9.52,
        "Total": 35.72
    },
    {
        "#": "15",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 36.97,
        "Natural": 27.46,
        "Social": 20.22,
        "Physical": 52.22,
        "SocialC": 23.55,
        "Temporal": 27.64,
        "Algebra": 22.86,
        "Geometry": 45.00,
        "Theory": 4.76,
        "Total": 27.05
    },
    {
        "#": "16",
        "Model": "LLaVA-V1.5-13B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 46.45,
        "Natural": 38.31,
        "Social": 27.87,
        "Physical": 67.78,
        "SocialC": 64.05,
        "Temporal": 49.59,
        "Algebra": 26.43,
        "Geometry": 30.00,
        "Theory": 23.81,
        "Total": 39.52
    },
    {
        "#": "17",
        "Model": "LLaVA-V1.5-13B",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 47.87,
        "Natural": 29.25,
        "Social": 27.23,
        "Physical": 68.89,
        "SocialC": 59.92,
        "Temporal": 47.15,
        "Algebra": 26.43,
        "Geometry": 36.25,
        "Theory": 9.52,
        "Total": 35.98
    },
    {
        "#": "18",
        "Model": "LLaVA-V1.5-13B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "13",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 38.86,
        "Natural": 31.55,
        "Social": 28.18,
        "Physical": 72.22,
        "SocialC": 61.57,
        "Temporal": 39.84,
        "Algebra": 29.29,
        "Geometry": 36.25,
        "Theory": 28.57,
        "Total": 36.45
    },
    {
        "#": "19",
        "Model": "CogVLM-17B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "17",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 52.61,
        "Natural": 37.42,
        "Social": 26.91,
        "Physical": 55.56,
        "SocialC": 54.13,
        "Temporal": 29.27,
        "Algebra": 29.29,
        "Geometry": 32.50,
        "Theory": 23.81,
        "Total": 37.19
    },
    {
        "#": "20",
        "Model": "CogVLM-17B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "17",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 51.18,
        "Natural": 43.81,
        "Social": 29.30,
        "Physical": 54.44,
        "SocialC": 39.26,
        "Temporal": 31.71,
        "Algebra": 35.71,
        "Geometry": 33.75,
        "Theory": 33.33,
        "Total": 38.91
    },
    {
        "#": "21",
        "Model": "CogVLM-17B",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "17",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 46.92,
        "Natural": 35.63,
        "Social": 25.80,
        "Physical": 48.89,
        "SocialC": 47.52,
        "Temporal": 38.21,
        "Algebra": 27.14,
        "Geometry": 31.25,
        "Theory": 19.05,
        "Total": 35.07
    },
    {
        "#": "22",
        "Model": "CogVLM-17B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "17",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 47.39,
        "Natural": 34.99,
        "Social": 25.80,
        "Physical": 62.22,
        "SocialC": 46.28,
        "Temporal": 35.77,
        "Algebra": 30.71,
        "Geometry": 37.50,
        "Theory": 23.81,
        "Total": 35.63
    },
    {
        "#": "23",
        "Model": "Gemini",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 73.93,
        "Natural": 41.25,
        "Social": 31.21,
        "Physical": 56.67,
        "SocialC": 71.49,
        "Temporal": 62.60,
        "Algebra": 30.71,
        "Geometry": 27.50,
        "Theory": 28.57,
        "Total": 45.17
    },
    {
        "#": "24",
        "Model": "Gemini",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 67.30,
        "Natural": 49.68,
        "Social": 36.31,
        "Physical": 68.89,
        "SocialC": 60.33,
        "Temporal": 66.67,
        "Algebra": 23.57,
        "Geometry": 21.25,
        "Theory": 9.52,
        "Total": 47.50
    },
    {
        "#": "25",
        "Model": "Gemini",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 49.29,
        "Natural": 43.68,
        "Social": 27.07,
        "Physical": 63.33,
        "SocialC": 57.85,
        "Temporal": 70.73,
        "Algebra": 28.57,
        "Geometry": 30.00,
        "Theory": 28.57,
        "Total": 41.85
    },
    {
        "#": "26",
        "Model": "Gemini",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 36.49,
        "Natural": 31.16,
        "Social": 27.39,
        "Physical": 71.11,
        "SocialC": 36.78,
        "Temporal": 55.28,
        "Algebra": 20.71,
        "Geometry": 16.25,
        "Theory": 0.00,
        "Total": 32.61
    },
    {
        "#": "27",
        "Model": "GPT4V",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 80.09,
        "Natural": 54.66,
        "Social": 43.95,
        "Physical": 87.78,
        "SocialC": 67.77,
        "Temporal": 82.11,
        "Algebra": 42.14,
        "Geometry": 43.75,
        "Theory": 42.86,
        "Total": 56.95
    },
    {
        "#": "28",
        "Model": "GPT4V",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 90.52,
        "Natural": 63.09,
        "Social": 46.97,
        "Physical": 83.33,
        "SocialC": 75.21,
        "Temporal": 82.93,
        "Algebra": 45.71,
        "Geometry": 50.00,
        "Theory": 38.10,
        "Total": 62.60
    },
    {
        "#": "19",
        "Model": "GPT4V",
        "Prompt": "Desp-CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 79.62,
        "Natural": 54.66,
        "Social": 36.94,
        "Physical": 88.89,
        "SocialC": 74.38,
        "Temporal": 73.98,
        "Algebra": 20.71,
        "Geometry": 32.50,
        "Theory": 33.33,
        "Total": 53.54
    },
    {
        "#": "30",
        "Model": "GPT4V",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 84.83,
        "Natural": 55.30,
        "Social": 39.81,
        "Physical": 80.00,
        "SocialC": 65.70,
        "Temporal": 81.30,
        "Algebra": 32.86,
        "Geometry": 21.25,
        "Theory": 28.57,
        "Total": 54.44
    },
    {
        "#": "31",
        "Model": "HuggingGPT",
        "Prompt": "-",
        "Setting": "tool-usage",
        "Size": "?",
        "Backbone": "gpt3.5",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 17.57,
        "Natural": 20.93,
        "Social": 10.33,
        "Physical": 8.70,
        "SocialC": 14.75,
        "Temporal": 9.76,
        "Algebra": 11.35,
        "Geometry": 22.50,
        "Theory": 9.52,
        "Total": 14.60
    },
    {
        "#": "32",
        "Model": "VisualChatGPT",
        "Prompt": "-",
        "Setting": "tool-usage",
        "Size": "?",
        "Backbone": "gpt3.5",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 30.09,
        "Natural": 36.28,
        "Social": 7.78,
        "Physical": 43.48,
        "SocialC": 29.92,
        "Temporal": 33.33,
        "Algebra": 21.99,
        "Geometry": 21.25,
        "Theory": 28.57,
        "Total": 25.92
    },
    {
        "#": "33",
        "Model": "IdealGPT",
        "Prompt": "-",
        "Setting": "tool-usage",
        "Size": "?",
        "Backbone": "gpt3.5",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 31.73,
        "Natural": 31.63,
        "Social": 26.23,
        "Physical": 56.52,
        "SocialC": 50.00,
        "Temporal": 26.83,
        "Algebra": 20.57,
        "Geometry": 30.00,
        "Theory": 38.10,
        "Total": 32.19
    },
    {
        "#": "34",
        "Model": "Chameleon",
        "Prompt": "-",
        "Setting": "tool-usage",
        "Size": "?",
        "Backbone": "gpt3.5",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 43.87,
        "Natural": 26.05,
        "Social": 25.44,
        "Physical": 39.13,
        "SocialC": 37.30,
        "Temporal": 48.78,
        "Algebra": 17.73,
        "Geometry": 26.25,
        "Theory": 23.81,
        "Total": 34.29
    },
    {
        "#": "35",
        "Model": "MM-CoT",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "0.1",
        "Backbone": "Flan-T5-base",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 41.71,
        "Natural": 46.49,
        "Social": 39.90,
        "Physical": 59.34,
        "SocialC": 60.91,
        "Temporal": 27.64,
        "Algebra": 48.57,
        "Geometry": 35.00,
        "Theory": 28.57,
        "Total": 44.85
    },
    {
        "#": "36",
        "Model": "MC-CoT",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "0.1",
        "Backbone": "Flan-T5-base",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 53.55,
        "Natural": 63.98,
        "Social": 43.56,
        "Physical": 61.54,
        "SocialC": 69.55,
        "Temporal": 29.27,
        "Algebra": 42.86,
        "Geometry": 33.75,
        "Theory": 28.57,
        "Total": 53.51
    },
    {
        "#": "37",
        "Model": "MM-CoT",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "0.7",
        "Backbone": "Flan-T5-Large",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 45.50,
        "Natural": 50.19,
        "Social": 43.56,
        "Physical": 63.74,
        "SocialC": 64.61,
        "Temporal": 33.33,
        "Algebra": 40.71,
        "Geometry": 61.25,
        "Theory": 28.57,
        "Total": 48.73
    },
    {
        "#": "38",
        "Model": "MMR",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "0.7",
        "Backbone": "Flan-T5-Large(MMR)",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 50.24,
        "Natural": 50.32,
        "Social": 43.56,
        "Physical": 76.92,
        "SocialC": 66.67,
        "Temporal": 31.71,
        "Algebra":  50.71,
        "Geometry": 65.00,
        "Theory": 38.10,
        "Total": 50.67
    },
    {
        "#": "39",
        "Model": "MC-CoT",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "0.7",
        "Backbone": "Flan-T5-Large",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 42.65,
        "Natural": 67.43,
        "Social": 50.56,
        "Physical": 58.24,
        "SocialC": 60.49,
        "Temporal": 56.10,
        "Algebra": 57.86,
        "Geometry": 62.50,
        "Theory": 14.29,
        "Total": 57.69
    },
    {
        "#": "40",
        "Model": "LLaMA-Adaper-7B",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "7",
        "Backbone": "LLaMA-Adaper-7B",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 62.56,
        "Natural": 72.29,
        "Social": 30.21,
        "Physical": 76.92,
        "SocialC": 59.67,
        "Temporal": 72.36,
        "Algebra": 30.71,
        "Geometry": 38.75,
        "Theory": 38.10,
        "Total": 54.89
    },
    {
        "#": "41",
        "Model": "LLaVA-V1.5-7B",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "7",
        "Backbone": "LLaVA-V1.5-7B",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 65.88,
        "Natural": 73.44,
        "Social": 35.14,
        "Physical": 80.22,
        "SocialC": 56.79,
        "Temporal": 67.48,
        "Algebra": 32.86,
        "Geometry": 47.50,
        "Theory": 19.05,
        "Total": 56.74
    },
    {
        "#": "42",
        "Model": "LLaVA-V1.5-13B",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "13",
        "Backbone": "LLaVA-V1.5-13B",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 68.72,
        "Natural": 72.41,
        "Social": 40.86,
        "Physical": 83.52,
        "SocialC": 64.61,
        "Temporal": 69.11,
        "Algebra": 35.71,
        "Geometry": 45.00,
        "Theory": 38.10,
        "Total": 59.50
    },
    {
        "#": "43",
        "Model": "CogVLM-17B",
        "Prompt": "-",
        "Setting": "fine-tuning",
        "Size": "17",
        "Backbone": "CogVLM-17B",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 65.88,
        "Natural": 77.52,
        "Social": 29.09,
        "Physical": 81.32,
        "SocialC": 65.43,
        "Temporal": 75.61,
        "Algebra": 35.71,
        "Geometry": 46.25,
        "Theory": 47.62,
        "Total": 58.25
    },
    {
        "#": "44",
        "Model": "GPT-4o-mini",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "GPT-4o-mini",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  61.9
    },
    {
        "#": "45",
        "Model": "GPT-4o",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "GPT-4o",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  64.3
    },
    {
        "#": "46",
        "Model": "Qwen2-VL-7B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  57.8
    },
    {
        "#": "47",
        "Model": "Mini-CPM-V-2-6-8B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "8B",
        "Backbone": "Mini-CPM-V-2-6-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  56.0
    },
    {
        "#": "48",
        "Model": "LLaVA-OneVision-7B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "LLaVA-OneVision-7B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  52.3
    },
    {
        "#": "49",
        "Model": "InternVL2-26B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "26B",
        "Backbone": "InternVL2-26B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 58.2
    },
    {
        "#": "50",
        "Model": "InternVL2-40B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "40B",
        "Backbone": "InternVL2-40B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 63.6
    },
    {
        "#": "51",
        "Model": "InternVL2-76B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "76B",
        "Backbone": "InternVL2-76B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 65.4
    },
    {
        "#": "52",
        "Model": "InternVL2-8B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 59.3
    },
    {
        "#": "53",
        "Model": "InternVL2-8B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 57.0
    },
    {
        "#": "54",
        "Model": "SFT",
        "Prompt": "Direct",
        "Setting": "fine-tuning",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total":  65.7
    },
    {
        "#": "55",
        "Model": "SFT",
        "Prompt": "CoT",
        "Setting": "fine-tuning",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 68.5
    },
    {
        "#": "56",
        "Model": "DPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 75.8
    },
    {
        "#": "57",
        "Model": "DPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 72.7
    },
    
    {
        "#": "58",
        "Model": "RSO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 74.2
    },
    {
        "#": "59",
        "Model": "RSO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 74.3
    },
    {
        "#": "60",
        "Model": "IPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 72.8
    },
    {
        "#": "61",
        "Model": "IPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 73.1
    },
    {
        "#": "62",
        "Model": "cDPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 76.2
    },
    {
        "#": "63",
        "Model": "cDPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 76.8
    },
    {
        "#": "64",
        "Model": "RobustDPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 75.1
    },
    {
        "#": "65",
        "Model": "RobustDPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 74.2
    },
    {
        "#": "66",
        "Model": "BCO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 78.1
    },
    {
        "#": "67",
        "Model": "BCO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 78.4
    },
    {
        "#": "68",
        "Model": "SPPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 66.2
    },
    {
        "#": "69",
        "Model": "SPPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 67.4
    },
    {
        "#": "70",
        "Model": "AOT",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 76.7
    },
    {
        "#": "71",
        "Model": "AOT",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 76.0
    },
    {
        "#": "72",
        "Model": "TR-DPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 75.9
    },
    {
        "#": "73",
        "Model": "TR-DPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 66.8
    },
    {
        "#": "74",
        "Model": "ORPO",
        "Prompt": "Direct",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 66.6
    },
    {
        "#": "75",
        "Model": "ORPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 73.9
    },
    {
        "#": "76",
        "Model": "MPO",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "8B",
        "Backbone": "InternVL2-8B",
        "Link": "https://arxiv.org/abs/2411.10442",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 79.2
    },
    {
        "#": "77",
        "Model": "GPT-4o",
        "Prompt": "IAT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "GPT-4o",
        "Link": "https://arxiv.org/abs/2410.03062",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 68
    },
    {
        "#": "78",
        "Model": "GPT-4o",
        "Prompt": "IBT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "GPT-4o",
        "Link": "https://arxiv.org/abs/2410.03062",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 72
    },
    {
        "#": "79",
        "Model": "Gemini-1.5-Flash",
        "Prompt": "IAT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "Gemini-1.5-Flash",
        "Link": "https://arxiv.org/abs/2410.03062",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 56
    },
    {
        "#": "80",
        "Model": "Gemini-1.5-Flash",
        "Prompt": "IBT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "Gemini-1.5-Flash",
        "Link": "https://arxiv.org/abs/2410.03062",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 61
    },
    {
        "#": "81",
        "Model": "Claude-3-haiku",
        "Prompt": "IAT",
        "Setting": "zero-shot",
        "Size": "?",
        "Backbone": "Claude-3-haiku",
        "Link": "https://arxiv.org/abs/2410.03062",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 50
    },
    {
        "#": "82",
        "Model": "Qwen-VL-7B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 31.28
    },
    {
        "#": "83",
        "Model": "Qwen-VL-7B",
        "Prompt": "CoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 30.73
    },
    {
        "#": "84",
        "Model": "Qwen-VL-7B",
        "Prompt": "Direct",
        "Setting": "fine-tuning",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 48.96
    },
    {
        "#": "85",
        "Model": "GPT-Distill",
        "Prompt": "CoT",
        "Setting": "fine-tuning",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 47.41
    },
    {
        "#": "86",
        "Model": "STaR",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 50.47
    },
    {
        "#": "87",
        "Model": "R3V",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "7B",
        "Backbone": "Qwen-VL-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 54.66
    },
    {
        "#": "88",
        "Model": "LLaVA-1.5-7B",
        "Prompt": "Direct",
        "Setting": "fine-tuning",
        "Size": "7B",
        "Backbone": "LLaVA-1.5-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 52.63
    },
    {
        "#": "85",
        "Model": "GPT-Distill",
        "Prompt": "CoT",
        "Setting": "fine-tuning",
        "Size": "7B",
        "Backbone": "LLaVA-1.5-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 47.54
    },
    {
        "#": "86",
        "Model": "STaR",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "7B",
        "Backbone": "LLaVA-1.5-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 54.06
    },
    {
        "#": "87",
        "Model": "R3V",
        "Prompt": "CoT",
        "Setting": "preference-optimization",
        "Size": "7B",
        "Backbone": "LLaVA-1.5-7B",
        "Link": "https://arxiv.org/abs/2411.00855",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 56.08
    },
    {
        "#": "88",
        "Model": "Chameleon-7B",
        "Prompt": "Direct",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 26.7
    },
    {
        "#": "89",
        "Model": "Chameleon-7B",
        "Prompt": "Direct",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 19.8
    },
    {
        "#": "90",
        "Model": "Chameleon-7B",
        "Prompt": "MM-CoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 28.9
    },
    {
        "#": "91",
        "Model": "Chameleon-7B",
        "Prompt": "MM-CoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 29.5
    },
    {
        "#": "92",
        "Model": "Chameleon-7B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 29.4
    },
    {
        "#": "93",
        "Model": "Chameleon-7B",
        "Prompt": "CCoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 30.1
    },
    {
        "#": "94",
        "Model": "Chameleon-7B",
        "Prompt": "DDCoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 28.6
    },
    {
        "#": "95",
        "Model": "Chameleon-7B",
        "Prompt": "DDCoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 29.8
    },
    {
        "#": "96",
        "Model": "Chameleon-7B",
        "Prompt": "SCAFFOLD",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 29.6
    },
    {
        "#": "97",
        "Model": "Chameleon-7B",
        "Prompt": "SCAFFOLD",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 31.1
    },
    {
        "#": "98",
        "Model": "Chameleon-7B",
        "Prompt": "ICoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 29.8
    },
    {
        "#": "99",
        "Model": "Chameleon-7B",
        "Prompt": "ICoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Chameleon-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 33.6
    },
    {
        "#": "100",
        "Model": "Qwen2-VL-7B",
        "Prompt": "Direct",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 38.7
    },
    {
        "#": "101",
        "Model": "Qwen2-VL-7B",
        "Prompt": "MM-CoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 37.5
    },
    {
        "#": "102",
        "Model": "Qwen2-VL-7B",
        "Prompt": "MM-CoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 40.3
    },
    {
        "#": "103",
        "Model": "Qwen2-VL-7B",
        "Prompt": "CCoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 38.5
    },
    {
        "#": "104",
        "Model": "Qwen2-VL-7B",
        "Prompt": "CCoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 39.1
    },
    {
        "#": "105",
        "Model": "Qwen2-VL-7B",
        "Prompt": "DDCoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 39.1
    },
    {
        "#": "106",
        "Model": "Qwen2-VL-7B",
        "Prompt": "DDCoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 38.9
    },
    {
        "#": "107",
        "Model": "Qwen2-VL-7B",
        "Prompt": "SCAFFOLD",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 39.5
    },
    {
        "#": "108",
        "Model": "Qwen2-VL-7B",
        "Prompt": "SCAFFOLD",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 40.2
    },
    {
        "#": "109",
        "Model": "Qwen2-VL-7B",
        "Prompt": "ICoT",
        "Setting": "zero-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 40.2
    },
    {
        "#": "110",
        "Model": "Qwen2-VL-7B",
        "Prompt": "ICoT",
        "Setting": "1-shot",
        "Size": "7B",
        "Backbone": "Qwen2-VL-7B",
        "Link": "https://arxiv.org/abs/2411.19488",
        "Lang": "-",
        "Natural": "-",
        "Social": "-",
        "Physical": "-",
        "SocialC": "-",
        "Temporal": "-",
        "Algebra": "-",
        "Geometry": "-",
        "Theory": "-",
        "Total": 41.2
    },
    {
        "#": "*",
        "Model": "Human Performance",
        "Prompt": "-",
        "Setting": "-",
        "Size": "-",
        "Backbone": "-",
        "Link": "https://aclanthology.org/2024.acl-long.446/",
        "Lang": 97.63,
        "Natural": 91.70,
        "Social": 87.92,
        "Physical": 97.80,
        "SocialC": 94.24,
        "Temporal": 91.87,
        "Algebra": 85.71,
        "Geometry": 90.00,
        "Theory": 76.19,
        "Total": 91.17
    }
]
